import Head from "next/head";
import styles from "../styles/Home.module.css";
import Third from "./Third";
import First from "./First";
import Faq from "./Faq";
import Legendaries from "./Legendaries";
import Krutilka from "./Krutilka";
import Team from "./Team";
import Roadmap from "./Roadmap";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <First />

      <Third />

      <Legendaries />
      <Krutilka />
      <Team />
      <Roadmap />

      <Faq />
    </div>
  );
}
