import Head from "next/head";
import styles from "../styles/Home.module.css";
import About from "./About";
import First from "./First";
import Faq from "./Faq";
import Legendaries from "./Legendaries";
import Krutilka from "./Krutilka";
import Team from "./Team";
import Roadmap from "./Roadmap";
import MobilePreview from "./MobilePreview";
import { useEffect, useState, useCallback } from "react";

const useMediaQuery = (width) => {
  const [targetReached, setTargetReached] = useState(false);

  const updateTarget = useCallback((e) => {
    if (e.matches) {
      setTargetReached(true);
    } else {
      setTargetReached(false);
    }
  }, []);

  useEffect(() => {
    const media = window.matchMedia(`(max-width: ${width}px)`);
    media.addEventListener("change", updateTarget);

    // Check on mount (callback is not called until a change occurs)
    if (media.matches) {
      setTargetReached(true);
    }

    return () => media.removeEventListener("change", updateTarget);
  }, []);

  return targetReached;
};

export default function Home() {
  const isBreakpoint = useMediaQuery(768);
  return (
    <>
      {isBreakpoint ? (
        <MobilePreview />
      ) : (
        <div className={styles.container}>
          <Head>
            <title>Create Next App </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <First />

          <About />

          <Legendaries />

          <Krutilka />
          <Team />
          <Roadmap />

          <Faq />
        </div>
      )}
    </>
  );
}
